{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'mr-box-peripheral-board' %}
{% set LIB_NAME = 'MrBoxPeripheralBoard' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
  number: 0
  noarch: python
  entry_points:
    - mr-box-peripheral-board-upload = mr_box_peripheral_board.bin.upload:upload
  script:
    # Generate Arduino code
    - python file_handler.py {{ SRC_DIR }} {{ PREFIX }} {{ PKG_NAME }}
    # Run setup
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python {{ python }}
    - path-helpers
    - conda-helpers
    - platformio-helpers
    - nanopb-helpers
    - platformio
    - dropbot-headers
    - base-node
    - base-node-dev
    - base-node-rpc
    - base-node-rpc-dev
    - pip

#     Split into `noarch` C++ header package and platform-specific Python
#     package.
outputs:
  - name: {{ PKG_NAME }}-dev
    noarch: generic
    files:
      - share
    requirements:
      run:
        - dropbot-headers
        - base-node
        - base-node-dev
        - base-node-rpc
        - base-node-rpc-dev
        - platformio
  - name: {{ PKG_NAME }}
    noarch: python
    files:
      - {{ SP_DIR }}/{{ MODULE_NAME }}
    requirements:
      run:
        - python >=3.6 
        - {{ pin_subpackage(PKG_NAME + '-dev', max_pin='x.x') }}
        - asyncio-helpers
        - base-node
        - base-node-dev
        - base-node-rpc
        - base-node-rpc-dev
        - conda-helpers
        - logging-helpers
        - nanopb-helpers
        - path-helpers
        - platformio-helpers
        - protobuf
        - serial-device
    test:
      imports:
        - mr_box_peripheral_board
        - mr_box_peripheral_board._version
        - mr_box_peripheral_board.bin
        - mr_box_peripheral_board.proxy

about:
  home: https://github.com/wheeler-microfluidics/mr-box-peripheral-board.py
  license: MIT
  summary: Peripheral board firmware

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
#  git_url: ../
  path: ..