# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mr_box_config.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'mr_box_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13mr_box_config.proto\x12\x17mr_box_peripheral_board\"\xdc\x01\n\x06\x43onfig\x12\x0c\n\x02id\x18\x04 \x01(\t:\x00\x12\x1f\n\x14zstage_down_position\x18\x32 \x01(\x02:\x01\x30\x12 \n\x12zstage_up_position\x18\x33 \x01(\x02:\x04\x31\x30.1\x12 \n\x13pmt_control_voltage\x18\x34 \x01(\r:\x03\x39\x30\x30\x12\x1c\n\x11pmt_sampling_rate\x18\x35 \x01(\r:\x01\x31\x12\"\n\x10pmt_sys_gain_cal\x18\x36 \x01(\r:\x08\x31\x36\x37\x37\x37\x32\x31\x35\x12\x1d\n\x12pmt_sys_offset_cal\x18\x37 \x01(\r:\x01\x30')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mr_box_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIG']._serialized_start=49
  _globals['_CONFIG']._serialized_end=269
# @@protoc_insertion_point(module_scope)
